INSERT INTO CPS (PlayerID, DateCalculated, CPS)
VALUES (1, DATE_SUB(NOW(), INTERVAL 1 DAY), 69);

INSERT INTO CPS (PlayerID, DateCalculated, CPS)
VALUES (1, DATE_SUB(NOW(), INTERVAL 2 DAY), 567);

INSERT INTO CPS (PlayerID, DateCalculated, CPS)
VALUES (1, DATE_SUB(NOW(), INTERVAL 3 DAY), 120);

INSERT INTO CPS (PlayerID, DateCalculated, CPS)
VALUES (1, DATE_SUB(NOW(), INTERVAL 4 DAY), 300);



